// Generated by `pnpm manifests`. Do not edit by hand.
import type { DemoCatalogEntry, DemoManifest } from '../../lib/demos/types';
import catalog from './index.json';
import m0 from './agency-03.json';
import m1 from './coffee-shop.json';
import m2 from './dentico.json';
import m3 from './fitclub.json';
import m4 from './online-course-02.json';
import m5 from './real-estate-v2.json';

export const DEMO_CATALOG = catalog as unknown as DemoCatalogEntry[];

export const DEMO_MANIFESTS: Record<string, DemoManifest> = {
	'agency-03': m0 as unknown as DemoManifest,
	'coffee-shop': m1 as unknown as DemoManifest,
	'dentico': m2 as unknown as DemoManifest,
	'fitclub': m3 as unknown as DemoManifest,
	'online-course-02': m4 as unknown as DemoManifest,
	'real-estate-v2': m5 as unknown as DemoManifest,
};
